FROM rocker/rstudio:4.3.1

COPY shiny-server.conf /etc/shiny-server/

RUN apt-get update -qq && \
    apt-get install -y \
    pkg-config \
    procps \
    libnlopt-dev \
    libmariadb-dev \
    zlib1g-dev \
    libssh2-1-dev \
    libxml2-dev \
    curl \
    libpng-dev \
    sudo \
    wget \
    git

COPY add /etc/cont-init.d/add
RUN export ADD=shiny && bash /etc/cont-init.d/add

RUN R -e "install.packages('readr', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('shiny', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('shinyjs', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('DT', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('formattable', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('plyr', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('shinyBS', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('markdown', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('remotes', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('htmltools', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('ggplot2', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('drc', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('plotly', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('ggsci', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('lemon', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('assertthat', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('dplyr', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('magrittr', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "install.packages('purrr', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"

RUN R -e "install.packages('BiocManager', repos = 'https://packagemanager.posit.co/cran/2023-06-01')"
RUN R -e "BiocManager::install('SummarizedExperiment')"
